---
- name: Ensure systemd-timesyncd is installed
  ansible.builtin.apt:
    name: systemd-timesyncd
    state: present
    update_cache: yes

- name: Ensure NTP is enabled
  ansible.builtin.command: timedatectl set-ntp true
  become: yes

- name: Restart timesyncd service
  ansible.builtin.service:
    name: systemd-timesyncd
    state: restarted
    enabled: yes
