---
- name: Ensure ufw is installed
  ansible.builtin.apt:
    name: ufw
    state: present
    update_cache: yes

- name: Allow SSH (port 22)
  community.general.ufw:
    rule: allow
    port: '22'

- name: Allow HTTP (port 80)
  community.general.ufw:
    rule: allow
    port: '80'

- name: Deny all other incoming connections
  community.general.ufw:
    direction: incoming
    policy: deny

- name: Enable UFW firewall
  community.general.ufw:
    state: enabled
